const config = require('./config')
const express = require('express')
const app = express()
app.use('/vendor', express.static('./packages/shared/public/libs/dll/development'))
app.listen(config.development.dllPort)
